### ISSUE TITLE
Need to Change Colors in APP

### ISSUE THREAD

**Issue by hardikvadgama** [abhinav3398/talent-unrivelled#1]
Use **Black** Color for the Menu, it will be Dark theme by Default.

**Comment by abhinav3398** [comment]
![theme](https://user-images.githubusercontent.com/34549766/89710285-1eeb8380-d99f-11ea-8ebe-76fb358e0973.jpg)
how's this theme?

**Comment by hardikvadgama** [comment]
It's Good will add other features continuously,  for now this is good!
